#' vrmd
#' view as Rmd
#' @examples \dontrun{
#'   #toCiteRoxyStart
#'   # library(ftlPlot)
#'   library(logger)
#'   library(data.table)
#'   
#'   vrmdQuick(paste0("testReport", hdatestamp()))
#'   vrmd(section = list(sectionIdUnique01 = "Section header"))
#'   vrmd("renderview")
#'   vrmd(rmdText = list(rmdTextLineID001 = c("explanation in rmd/md format")))
#'   plot(1:10)
#'   vrmd("add", p = recordPlot(), chunkId = "base plot")
#'   vrmd("add", p = recordPlot(), chunkId = "base plot 2")
#'   vrmd("info")
#'   vrmd("restart", restart = 10)
#'   vrmd("docuFun", docuFun = "R/vrmd.R", toCiteStart = "#toCiteRoxyStart")
#'   vrmd("info")
#'   vrmd("DT", dfg = data.frame(c1 = 1:110, c2 = 110:1), rowsPerPage = 7)
#'   vrmd("renderview")
#'   vrmd("dirs3")
#'   store <- TSS3Store()
#'   reportsMade <- vrmd("dirs3", storeReport = store, folderS3 = "")
#'   ppath <- getFolder(store, file.path("AdHocReports")
#'                           , path = file.path(getCacheDir(), "reports2022")) 
#'   #toCiteRoxyEnd
#' }
#' @param overwrite Normally 'render' will overwrite the HTML by re-rendering the Rmd. 'overwrite' skips that
#' @importFrom rmarkdown render
#' @import logger
# @import aphTsStore
#' @import kableExtra
#' @import knitr
#' @export
vrmd <- function(
    do = "nothing"  # "info"
    , p = NULL, ffpng.in=NULL, ffpng.out=NULL, file="tmp.ppt"
    , doTabbed = 0
    , tabbedSectionModifier = character(0)
    
    , togglePairs = list("toggle Format 1" = c("testtt", "testttnogrid"))[0]
    
    , repId = "global"
    , restartFrom = "openingChunk"
    , overwrite = TRUE 
    , htmlString = NULL # for do == "html"
    , dfg = NULL
    , scrollboxDim = c(800, 200)[0]
    , bsOptions = c("striped", "basic")[2]
    , kableStylingString = paste0('|> kable_styling(bootstrap_options = "'
                                  , bsOptions
                                  ,'", full_width = F, position = "left")')
    , i18n = NULL
    , DTquotedOptionsList = list(pageLength = pageLength
                                 , sDom = sDom)
    , pageLength = 50
    , sDom = c("lfrt", "lrt")[2]  # f is filter / search
    , DTescape = FALSE
    , docuFun = NULL
    , prepForLatex = FALSE
    , rmdLatexFile = NULL # autogenerated from docufun
    , toCiteStart = "# toCiteStart"
    , toCiteEnd = "auto" # "e.g. # toCiteEnd"
    , showComments = c("none", "all", "partial")[3]
    , dropLatexDrop = TRUE
    , showCode = TRUE
    , keepRoxygen = TRUE
    , outputStyle = "html"#, "ftlStyle"#, "blank")[1]
    , sectionNumbering = FALSE
    , storeReport = list()
    , res = invisible(character(0))
    , script = NULL, doscript = TRUE
    , scriptDir = "inst" #list.files("inst")[1]
    , scriptPackage = basename(getwd())
    , cacheDir = getCacheDir()
    , userName = "Hans Schepers" #Sys.getenv("USERNAME", "UNKNOWNUSER")
    , tmpdir = cacheDir #file.path(cacheDir, userName, "vrmdCache")
    , project = "HTMLreports_recent"
    , pushDir = file.path(cacheDir, project)
    # , githubPath = "https://github.com/bayer-int/"    
    , githubPath = "https://github.com/hansschepers/"
    , ffmd = "test.md"
    , ffhtml = NULL
    , outputFilename = paste0(repId, ".rmd")  #TODO not prepared ofr repId from g.repId
    , reportTitle = paste("Report: ", repId)        #TODO not prepared ofr repId from g.repId
    , ffrmd = file.path(tmpdir, outputFilename)
    , targetExtension = "html" # ifelse(tolower(outputStyle) == "word", "doc", "html")
    , output_file = gsub("rmd$", targetExtension, ffrmd, ignore.case = TRUE)
    , headerData = list(reportTitle = reportTitle
                        , reportSubtitle = ""
                        , output_format = NULL  # for render
                        , reportAuthor = tolower(userName))
    , folderS3 = paste0("User_", userName )
    , S3reportFileName = character()
    , pushReportFileName = character()
    , reportBasePathS3 = "AdHocReports"
    # per chunk
    , chunkTitle = NULL
    , chunkId = htimestamp(digits.secs = 3)
    , chartClassAdded = "pggs"
    , tableId = chunkId # paste0("table_", htimestamp())
    , chunkCaption = NULL
    , chunkText = "plot description in Rmd\n"
    , chunkPrefix = ""  # '###'
    , chunkSectionModifier = "{-}"  # paste0(' {-#',chunkId,'}')
    
    , my_temp_file = file.path(tmpdir, paste0(make.names3(chunkId), ".png"))
    
    , section = NULL, rmdText = NULL
    , sectionLevel = 2
    , quiet = TRUE
    , writeImmediately = TRUE
    # for dev2png
    , ggwidth = 14, ggheight = 8  # inch
    , childWidth2 = "100%"
    , dpi = 96
    , insideUI = FALSE
    , chapter = character(0) # chapter = "test"
    , doX = TRUE
    , chunkBase = character()
){
  
  if (exists("g.chunkBase")) {chunkBase = g.chunkBase}
  if (length(chunkBase)){
    if (inherits(chunkBase,  "Date")) chunkBase  <- as.character(chunkBase)
    if (regexpr(chunkBase, chunkId)[1] < 0){
      chunkId <- paste0(chunkBase, chunkId)
    }
  }
  
  # if (grepl("off", do)){
  #   message("disabling vrmd")
  #   vrmd <<- function(do, ...) {
  #     if (grepl("info", do)){
  #       # ftlPlot :: vrmd("info")
  #       message("vrmd is paused!!")
  #     }
  #     if (grepl("on", do)){
  #       message("vrmd re-instated")
  #       if ("ftlPlot" %in% loadedNamespaces()){
  #         # vrmd <<- ftlPlot :: vrmd
  #       } else {
  #         return("vrmd source not found")
  #       }
  #       return(invisible(0))
  #     } else {
  #       message("vrmd is already off")
  #     }
  #     return(invisible(0))
  #   }
  #   return(invisible(0))
  # }
  # if (grepl("on", do)){
  #   message("vrmd is already on")
  # }
  
  if (substr(scriptPackage, 1, 4) != "aph-"){
    scriptPackage <- paste0("aph-", scriptPackage)
  }
  # githubPath <- "https://github.platforms.engineering/DigitalHorticulture/"
  
  # deRuiterStyle
  tabColors <- ftlPalette()
  # tabColors <- c("blue", "red", "green", "orange", "yellow")
  
  if (inherits(chunkCaption, "Date")) chunkCaption <- as.character(chunkCaption)
  if (inherits(tableId,      "Date")) tableId      <- as.character(tableId)
  if (inherits(chunkId,      "Date")) chunkId      <- as.character(chunkId)
  
  if (!is.null(chunkTitle)){
    if (is.null(chunkId)){
      chunkId <- chunkTitle
    }
    # chunkCaption <- chunkTitle
  }
  if (chartClassAdded[1] == "pggs") {
    chartClassAdded <- make.names3(chunkId)
    log_trace("chartClassAdded {chartClassAdded}")
  }
  
  if (doTabbed == 0 & exists("g.doTabbed", envir = .GlobalEnv)){
    doTabbed <- g.doTabbed
  }
  do <- tolower(do)
  if (tolower(headerData$reportAuthor) == "Hans Schepers") {
    headerData$reportAuthor <- "Hans.Schepers@gmail.com"
  }
  # if (tolower(headerData$reportAuthor) == "gkmsz") {
  #   headerData$reportAuthor <- "Farshad.Goldoust@bayer.com"
  # }
  # if (tolower(headerData$reportAuthor) == "tdoes1") {
  #   headerData$reportAuthor <- "Timo.Doeswijk@bayer.com"
  # }
  # Sys.getenv("PLOTLY_MATHJAX_PATH")
  if (exists("g.repId")){
    if (repId == "global"){
      repId <- g.repId
      log_trace("using report name {repId}")
    } 
  }
  
  log_trace("repId: {repId}, chunkId: {chunkId}")
  log_trace("tempdir: { tmpdir}, {my_temp_file}")
  if (!dir.exists(tmpdir)) {
    log_warn("tempdir not found: { tmpdir}, but dir has been created!")
    dir.create(tmpdir, recursive = TRUE)
    # tmpdir <- tempdir()
    my_temp_file = file.path(tmpdir, paste0(make.names3(chunkId), ".png"))
    log_warn("my_temp_file now: {my_temp_file}")
  }
  
  #zzz
  if (doTabbed == 0){
    tabColorChangeRmdAfter <- character(0)
    tabColorChangeRmd <- character(0)
    sectionModifier <- character(0)
  } else {
    tabColorChangeRmd      <- aphTabColorCss(tabColors[sectionLevel-1])
    tabColorChangeRmdAfter <- aphTabColorCss(tabColors[sectionLevel])
    # cat(tabColorChangeRmd)
    sectionModifier <- paste0(' {.tabset .tabset-fade .tabset-pills ', tabbedSectionModifier, '}')
  }
  
  
  if (is.null(chunkCaption)) {
    # chunkCaption <- chunkId  # 20220729
    if (grepl("dfg", do)) chunkCaption <- tableId
  }
  
  # if (!exists("g.addRmd")) {
  #   g.addRmd = F
  #   g.addRmd <<- g.addRmd
  # }
  # # log_info("g.addRmd ", g.addRmd)
  # if (!g.addRmd) return(invisible(NULL))
  if (!dir.exists(tmpdir)) dir.create(tmpdir, recursive = TRUE)
  
  if (nchar(chunkPrefix) == 0){
    chunkSectionModifier <- character(0)
  }
  
  # write Rmd file to disk
  writeRmd <- function(myGlobalRmd
                       , ffrmd = myGlobalRmd$ffrmd  # [[repId]] ?
                       , exclude = c("ffrmd", "output_file", "tmpdir"
                                     , "renderResult", "headerData")
  ){
    toInclude <- setdiff(names(myGlobalRmd), exclude)  #[[repId]] TODO 20241014
    str(toInclude)
    cat(unlist(myGlobalRmd[toInclude]), file = ffrmd)
  }
  
  
  # if (!exists("script")) {doscript=FALSE ; script = " "}
  if (is.null(script)) {doscript=FALSE ; script = " "}
  
  # init for myGlobalRmd[[repId]]
  if (!exists("g.repId")) {
    g.repId <- "nonExistenT"  # NOT with <<- ! so not exported
    
  }
  
  if (grepl("help", do)){
    help(vrmd)
    return(res)
  }
  
  ############################################### INIT #########################
  if (grepl("init", do) & ((repId == "global") | (repId == g.repId))){
    message("please choose a new meaningful repId")
    return(NULL)
  }
  
  
  
  if (grepl("info", do)){
    # print(ls(pattern = "myGlobalRmd|^g\\.", envir = .GlobalEnv))
    gDotObjects <- ls(pattern = "^g\\.", envir = .GlobalEnv)
    gDotObjects <- intersect(gDotObjects, c("g.addppt", "g.addRmd", "g.doplot", "g.ggly", "g.repId"))
    print(unlist(mget(gDotObjects, envir = .GlobalEnv)))
    
    if (exists("myGlobalRmd")) {
      # repId <- names(myGlobalRmd)[1]
      message("reportId's: ", paste(names(myGlobalRmd), collapse = " | "))
      
      if (repId %in% names(myGlobalRmd)){
        
        if (!quiet) print(strList(myGlobalRmd[[repId]]))
        if (grepl("infoheader", do)) {
          if (all(c("headerData", "ffrmd") %in% names(myGlobalRmd[[repId]]))){
            print(myGlobalRmd[[repId]]$headerData)
            print(myGlobalRmd[[repId]]$ffrmd)
          } else {
            message("no header and rmd file name")
          }
        }
        return(as.data.frame(strList(myGlobalRmd[[repId]])))
        
      } else {
        
        nn <- length(myGlobalRmd)
        print(glue::glue("there are {nn} reports:"))
        print(names(myGlobalRmd))
        print(glue::glue("suggestion: \nvrmd(\"info\", repId = \"{names(myGlobalRmd)[1]}\")"))
        return(as.data.frame(strList(myGlobalRmd)))
      }
      
    } else {
      
      return("no object myGlobalRmd")
      # help(vrmd)
    }
  }
  
  
  
  if (grepl("init", do) | (!exists("myGlobalRmd")) ) {
    if (grepl("clean", do) | !exists("myGlobalRmd")) {
      if (exists("myGlobalRmd")) {
        log_warn("making backup of myGlobalRmd  as myGlobalRmd2 ...")
        myGlobalRmd2 <<- myGlobalRmd
      } #else {
      message("forcing init")
      log_warn("Initializing new !! Global !! Rmd list object (myGlobalRmd)...")
      do <- paste0(do, "init")
      myGlobalRmd <- list()
      #}
      # message("vrmd non initialized yet, please use 'vrmdQuick(<repId>)' first")
      # return("errror")
    }
  }
  
  
  if (grepl("init", do) ) {
    {
      sectionNumberingRow <- paste0('    number_sections: '
                                    , ifelse(sectionNumbering, 'true', 'false'))
      outputHeaderRow <- switch(tolower(outputStyle)
                                , blank = NULL
                                , gv = NULL
                                , pres     = "output: ioslides"
                                , ioslides = "output: ioslides"
                                # , deruiterstyle = "output: deRuiterStyle :: html_report"
                                , word = paste0('output:\n    word_document:'
                                                , '\n      reference_docx: !expr system.file(package = "aphReporting", "msWordTemplates", "wordStylesReference01.docx")'
                                                , '\n      toc: true\n      toc_depth: 2\n      number_sections: true')
                                # default
                                , paste0("output:\n  html_document:\n", sectionNumberingRow)
      )
      
      
      header <- paste0(
        '---
title: "`r headerData$reportTitle`"
subtitle: "`r headerData$reportSubtitle`"
author: "`r headerData$reportAuthor`"
date: "',format(Sys.Date(), "%B %d, %Y") ,'"\n',
        outputHeaderRow, '\n',
        '---\n'
        # , aphTabColorCss(tabColors[1])
        , '\n\n'
      )
      
      
      meta <- paste("made by", userName, getwd())
      {
        openingChunk <- paste0('
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)\n\
```\n\n<!-- ********************* ', meta,' --> \n\n')
      }
    }
    
    
    myGlobalRmd[[repId]] <- list(ffrmd = ffrmd
                                 , output_file = output_file
                                 , tmpdir = tmpdir
                                 , renderResult = FALSE
                                 , headerData = headerData
                                 , header = header
                                 , openingChunk = openingChunk
    )
    # bibliography: "`r system.file('templates', 'r.bib', package = 'deRuiterStyle')`"
    log_info("initialized myGlobalRmd and put in .GlobalEnv")
    myGlobalRmd <<- myGlobalRmd
    res <- c(res, "init done")
    if (isTRUE(insideUI)) return(NULL)
  }
  
  
  if (length(togglePairs)){
    buttons <- character(0)
    buttons <- paste0('<button onclick="aphJsToggle()">', names(togglePairs)[1],'</button>')
    myGlobalRmd[[repId]][paste0("button_", names(togglePairs)[1])] <- paste0('\n\n', buttons, '\n\n')
    res <- c(res, "buttons set")
    # }
    # if (length(togglePairs)){
    toggleStyleScript <- paste0(
      '\n\n<script> function aphJsToggle() {  '
      , 'var x = document.getElementById("', togglePairs[[1]][1],'");'
      , 'var x2 = document.getElementById("', togglePairs[[1]][2],'");'
      , '\nif (x2.style.display === "block") {    x2.style.display = "none";  } else {    x2.style.display = "block";  }'
      , '\nif (x.style.display === "none") {    x.style.display = "block";  } else {    x.style.display = "none";  }'
      , '\n}'
      # hide second element, outside the aphJsToggle() function
      , '\nvar x3 = document.getElementById("', togglePairs[[1]][2],'"); x3.style.display = "block"; '
      , '\n</script>\n\n')
    # cat(toggleStyleScript)
    
    myGlobalRmd[[repId]][names(togglePairs)[1]] <- paste0('\n\n', toggleStyleScript, '\n\n')
    res <- c(res, "togglePairs has been set")
  }
  
  
  
  ############################################### SECTION ######################
  if (length(chapter)){
    # chapter <- "1. CLIMATE"
    sectionTag <- paste0("autoChapter_", chapter)
    closerTag <- paste0("autoCloser_", chapter)
    
    # if (F){
    #   if (is.null(i18n)){
    #     i18n <- starti18n(lang.oi = "nl")
    #     i18n$dict <- data.table::as.data.table(
    #       add2Dict(i18n$dict, list(c(en = "climate", nl = "KLIMAAT")))
    #     )
    #     # grep("climate", i18n$dict$en, ignore.case = TRUE, value = TRUE)
    #   }
    #   
    #   # tail(i18n$dict)
    #   prefix   <- sub("([0-9\\. :-_]*) (.*)", "\\1", chapter)
    #   coreWord <- sub("([0-9\\. :-_]*) (.*)", "\\2", chapter)
    #   chapter <- paste(prefix, coreWord)
    #   # chapter <- paste(prefix, i18n_t2(coreWord))  # aphMetadata :::
    #   chapter
    # }
    
    vrmd(section = as.list(setNames(chapter, sectionTag)), sectionLevel = 2, doTabbed = 3)
    if (doX) vrmd(section = as.list(setNames("[X]", closerTag)), sectionLevel = 3, doTabbed = 3)
    return("chapter set")
  }
  
  
  if (!is.null(section)){
    section <- as.list(section)
    if(!inherits(section, "list")){
      return("(sub)section must be a list")
    }
    sectionModifier <- paste0(' {-#',names(section),'}')
    
    if (doTabbed == 0){
      tabColorChangeRmdAfter <- character(0)
      tabColorChangeRmd <- character(0)
      sectionModifier <- character(0) 
    } else {
      tabColorChangeRmdAfter <- character(0)
      tabColorChangeRmd <- character(0)
      # tabColorChangeRmd      <- aphTabColorCss(tabColors[sectionLevel-1])
      # tabColorChangeRmdAfter <- aphTabColorCss(tabColors[sectionLevel])
      # cat(tabColorChangeRmd)
      # sectionModifier <- paste0(' {.tabset .tabset-fade .tabset-pills ', tabbedSectionModifier, '}')
      sectionModifier <- paste0(' {.tabset ', tabbedSectionModifier, '}')
    }
    
    # sectionModifier <- character(0)
    hashes <- paste0(rep("#", sectionLevel), collapse = "")
    myGlobalRmd[[repId]][names(section)] <- paste0(tabColorChangeRmd,
                                                   '\n\n', hashes,' '
                                                   , section, sectionModifier, '\n\n'
                                                   , tabColorChangeRmdAfter
    )
    res <- c(res, "section has been set")
    if (isTRUE(insideUI)) return(NULL)
  }
  
  
  ############################################### RESTART ######################
  if (grepl("restart", do)){
    if (is.numeric(restartFrom)){
      indexOpening <- restartFrom
    } else {
      indexOpening <- which(restartFrom == names(myGlobalRmd[[repId]]))[1]
    }
    if (!is.na(indexOpening)) {
      if (indexOpening < length(myGlobalRmd[[repId]])){
        myGlobalRmd[[repId]][(indexOpening+1) : length(myGlobalRmd[[repId]])] <- NULL
      }
      print(strList(myGlobalRmd[[repId]]))
    } else {
      log_warn("already restarted the myGlobalRmd[[repId]]")
    }
    res <- c(res, "did a restart")
  }
  
  
  if (grepl("script", do)){
    # system.file(scriptDir, package = scriptPackage)
    # system.file(scriptDir, script, package = scriptPackage)
    ffr <- system.file(scriptDir, script, package = scriptPackage)
    log_info("checking existence of script {ffr} in package: {ffr} {file.exists(ffr)}")
    if (file.exists(ffr)) {
      # script <- sub(.libPaths(), "", ffr)
      ffr <- paste0(githubPath, scriptPackage,"/tree/main/inst")
      ffr <- file.path(ffr, scriptDir, script)
      log_info("linking to script location on Github: {ffr}")
      myGlobalRmd[[repId]]$headerData$reportSubtitle <- 
        paste0("script: [", script, "](", ffr,")")
    } else {
      message("file not found: ", ffr)
      myGlobalRmd[[repId]]$headerData$reportSubtitle <- 
        paste0("script: ", script)
    }
    myGlobalRmd <<- myGlobalRmd
    res <- c(res, "added script")
  }
  
  
  if (grepl("docufun", do) & !is.null(docuFun)){
    log_info("documenting key function extract {docuFun}" )
    
    if (file.exists(docuFun)){
      # a script
      ffr <- docuFun
    } else {
      # a function
      FUN <- match.fun(sub("Sim$", "", docuFun))
      ffr <- utils::getSrcFilename(FUN, full.names = TRUE)
    }
    ffr <- sub("~/aphDH", githubPath, ffr)
    # ffr <- sub("/inst/",  "/blob/main/inst/", ffr)
    ffr <- sub("^inst/",  paste0(githubPath, scriptPackage,"/blob/main/inst/"), ffr)
    ffr <- sub("^(\\.\\./)(.*/)(inst/)",  paste0(githubPath, "\\2", "blob/main/inst/"), ffr)
    ffr <- sub("^(\\.\\./)(.*/)(R/)",     paste0(githubPath, "\\2", "tree/main/R/"), ffr)
    ffr <- sub("^R/",  paste0(githubPath, scriptPackage, "/tree/main/R/"), ffr)
    log_trace("ffr: {ffr}")
    if (!length(ffr)) {
      log_error("no meaningful docufun filename found..")
    }
    if (grepl("^https", ffr)) {
      # ffr <- sub("/R/", "/tree/main/R/", ffr)
      log_info("linking to file location on Github: {ffr}")
    } else {
      ffr <- paste0("file:///", ffr)
      log_info("linking to file location on disk: {ffr}")
    }
    log_debug(ffr)
    
    if (showCode){
      textFromFile <- 
        extractSourceCodeHighlight(docuFun
                                   , showComments = showComments
                                   , keepRoxygen = keepRoxygen
                                   , toCiteStart = toCiteStart
                                   , toCiteEnd = toCiteEnd
                                   , prepForLatex = prepForLatex
                                   , dropLatexDrop = dropLatexDrop
        )
      textFromFile <- paste(textFromFile, collapse = "\n")
    } else {
      textFromFile <- ""
    }
    # textFromFile <<- .textFromFile
    .textFromFile <<- textFromFile
    if (prepForLatex){
      # rmdLatexFile <- NULL
      # docuFun <- "test"
      # docuFun <- modelId
      if (is.null(rmdLatexFile)){
        ffrmdbase <- paste0(docuFun
                            , gsub("[# .-]", "", toCiteStart)
                            , gsub("[# .-]", "", toCiteEnd)
                            , ".Rmd")
        rmdLatexFile <- file.path(cacheDir, ffrmdbase)
        if (file.exists(rmdLatexFile)){
          log_warn("making copy before overwriting {rmdLatexFile}")
          ww <- file.copy(rmdLatexFile, paste0(rmdLatexFile, ".b"), overwrite = TRUE)
        }
        log_warn("(over)writing {rmdLatexFile}")
        writeLines(textFromFile, rmdLatexFile)
      }
      child <- paste0(
        "used: [", docuFun, "](", ffr,")"
        ,"\n\n```{r child = "
        , '"',rmdLatexFile,'"'
        , ", out.width = \"1400px\""
        , "}"
        ,'\n\n```\n\n'
      )
      if (log_threshold() >= 450){
        print(child)
      }
      log_trace("*******************************")
    } else {
      child <- paste0(
        "used: [", docuFun, "](", ffr,")",
        "\n\n```{r results = FALSE, eval=FALSE, echo = TRUE}\n",
        textFromFile
        ,'\n```\n\n'
      )
    }
    
    chunkSection <- NULL
    tabbedPrefix <- ""
    if (doTabbed > 0){
      hashes <- paste0(rep("#", doTabbed), collapse = "")
      tabbedPrefix <- paste0("\n\n", hashes, " ", chunkId, "\n\n")
      chunkSection <- paste0(tabbedPrefix)#, '\n\n',chunkPrefix,' ', chunkId, chunkSectionModifier, '\n\n')
    }
    
    
    # myGlobalRmd[[repId]][docuFun] <- child
    # myGlobalRmd[[repId]][gsub("/", "", docuFun)] <- child
    myGlobalRmd[[repId]][make.names3(paste(
      docuFun
      , "Latex"
      , 0+prepForLatex
      , toCiteStart))] <- paste(chunkSection, child)
    res <- c(res, "added docufun")
  }
  
  
  
  if (grepl("html", do) | !is.null(htmlString)){
    
    chunkSection <- NULL
    tabbedPrefix <- ""
    if (doTabbed > 0){
      hashes <- paste0(rep("#", doTabbed), collapse = "")
      tabbedPrefix <- paste0("\n\n", hashes, " ", chunkId, "\n\n")
      chunkSection <- paste0(tabbedPrefix)#, '\n\n',chunkPrefix,' ', chunkId, chunkSectionModifier, '\n\n')
    }
    
    
    tableStart <- '```{r echo=FALSE}\nknitr::asis_output(htmltools::htmlPreserve(\"\n<div>\n'
    tableEnd <- '\n</div>\"\n))\n```'
    child <- gsub('"', '\\\\"', htmlString)
    child <- paste0(chunkSection, tableStart, child, tableEnd)
    attributes(child) <- list(knit_cacheable = NA, class = "knit_asis")
    myGlobalRmd[[repId]][chunkId] <- child
  }# attributes(child) <- list(format = "html", class = c("kableExtra", "knitr_kable"))
  
  
  
  if (grepl("dfg", do) | !is.null(dfg)){
    if (!require(kableExtra)) return("need kableExtra for tables")
    log_trace("inserting {tableId} with dim {paste(dim(dfg), collapse = ', ')}" )
    if (!"headerData" %in% names(myGlobalRmd[[repId]])){
      stop("no header, likely not initialized?")
    }
    myGlobalRmd[[repId]]$headerData[[tableId]] <- as.data.frame(dfg)
    
    
    chunkSection <- NULL
    tabbedPrefix <- ""
    if (doTabbed > 0){
      hashes <- paste0(rep("#", doTabbed), collapse = "")
      tabbedPrefix <- paste0("\n\n", hashes, " ", chunkId, "\n\n")
      chunkSection <- paste0(tabbedPrefix)#, '\n\n',chunkPrefix,' ', chunkId, chunkSectionModifier, '\n\n')
    }
    
    if (length(scrollboxDim) > 1){
      kableChainFunctions <- paste0(' |> scroll_box(width = "', scrollboxDim[1],'px", height = "', scrollboxDim[2],'px")')
    } else {
      kableChainFunctions <- ''
    }
    log_trace("vrmd|kableStylingString: {kableStylingString}")
    
    child <- paste0(
      chunkSection,
      "\n```{r echo = FALSE}\n",  #results = FALSE, eval=FALSE, echo = TRUE
      'kable(myGlobalRmd[[repId]]$headerData[["',tableId,'"]])'
      , kableStylingString
      , kableChainFunctions
      ,'\n```\n\n'
      , chunkCaption
      , '\n\n'
    )
    # ccc <- "<!--/html_preserve-->"
    # ccc <- NULL
    # tableStart <- paste0("\n\n",ccc,"\n<div>\n\n")
    # tableEnd <- paste0("\n\n</div>\n",ccc,"\n\n")
    # str(child)
    myGlobalRmd[[repId]][tableId] <- child
  }
  
  
  
  
  if (grepl("DT", do) & !is.null(dfg)){
    log_trace("DT- inserting {tableId} with dim {paste(dim(dfg), collapse = ', ')}" )
    if (!"headerData" %in% names(myGlobalRmd[[repId]])){
      stop("no header, likely not initialized?")
    }
    myGlobalRmd[[repId]]$headerData[[tableId]] <- as.data.frame(dfg)
    
    chunkSection <- NULL
    tabbedPrefix <- ""
    if (doTabbed > 0){
      hashes <- paste0(rep("#", doTabbed), collapse = "")
      tabbedPrefix <- paste0("\n\n", hashes, " ", chunkId, "\n\n")
      chunkSection <- paste0(tabbedPrefix)#, '\n\n',chunkPrefix,' ', chunkId, chunkSectionModifier, '\n\n')
    }
    
    if (nrow(dfg) <= DTquotedOptionsList$pageLength){
      DTquotedOptionsList$sDom <- sub("[lpf]", "", DTquotedOptionsList$sDom)
      # message(609)
    }
    child <- paste0(
      chunkSection,
      "\n```{r echo = FALSE}\n"  #results = FALSE, eval=FALSE, echo = TRUE
      , 'DT::datatable(myGlobalRmd[[repId]]$headerData[["',tableId,'"]]'
      , ', options = ', deparse(DTquotedOptionsList)
      , ', escape = ', DTescape
      , ')'
      , '\n```\n\n'
      , chunkCaption
      , '\n\n'
    )
    
    
    # child <- paste0(
    #   chunkSection,
    #   "\n```{r echo = FALSE}\n"  #results = FALSE, eval=FALSE, echo = TRUE
    #   , 'DT::datatable(myGlobalRmd[[repId]]$headerData[["',tableId,'"]]'
    #   , ', options = list(pageLength = ',rowsPerPage,'))'
    #   , '\n```\n\n'
    #   , chunkCaption
    #   , '\n\n'
    # )
    
    myGlobalRmd[[repId]][tableId] <- child
  }

  
  
  
  
  if (grepl("md", do) & file.exists(ffmd)){
    log_trace("md- inserting {ffmd} " )
    if (!"headerData" %in% names(myGlobalRmd[[repId]])){
      stop("no header, likely not initialized?")
    }
    
    chunkSection <- NULL
    tabbedPrefix <- ""
    if (doTabbed > 0){
      hashes <- paste0(rep("#", doTabbed), collapse = "")
      tabbedPrefix <- paste0("\n\n", hashes, " ", chunkId, "\n\n")
      chunkSection <- paste0(tabbedPrefix)#, '\n\n',chunkPrefix,' ', chunkId, chunkSectionModifier, '\n\n')
    }
    # 
    # mdcontent <- readLines(ffmd)
    child <- paste0(
      chunkSection,
      # "\n```{r echo = FALSE}\n"  #results = FALSE, eval=FALSE, echo = TRUE
      knitr::knit_child(ffmd)
      # , htmltools::includeMarkdown((paste0(mdcontent, collapse = "\n")))
      # , '\n```\n\n'
      # , chunkCaption
      # , '\n\n'
    )
    myGlobalRmd[[repId]][chunkId] <- child
  }
  
  
  
  
  if (grepl("add", do) & !is.null(my_temp_file)) {
    if (is.null(p)) return("p is NULL") # {p <- ggplot2::last_plot()}
    if (!length(ffhtml)){
      ffhtml <- paste0(tempfile(), ".html")
    }
    dev2pngArgList <- list(p = p
                           , ffpng.out = ASCIIfy(my_temp_file)  # png output file
                           , ggwidth = ggwidth
                           , ggheight = ggheight
                           # , relsize = relsize
                           # , pxwidth = pxwidth, pxheight = pxheight
                           # , aspect.ratio = aspect.ratio
                           , ffhtml = ffhtml  # html output / intermediate file, save as '.ffhtml'
                           , dpi = dpi)
    # 20230527
    suppressMessages(suppressWarnings({
      my_temp_file <- do.call(dev2png, dev2pngArgList)
    }))
    
    if (!exists("my_temp_file")) my_temp_file <- "test"
    # chunkRmdFileName <- paste0(make.names3(chunkId), ".Rmd")
    chunkRmdFileName <- file.path(tmpdir, paste0(make.names3(chunkId), ".Rmd")) #TODO 20241014
    
    doubleCaption <- NULL
    # doubleCaption <- paste0("\n\n", chunkCaption,"\n\n")
    # chunkRmdContent <- paste0('knitr::include_graphics("', my_temp_file,'", dpi = 1000)')
    chunkRmdContent <- paste0('!['
                              , chunkCaption
                              , '](', basename(my_temp_file), '){'
                              , 'width=', childWidth2
                              # , ';#', chartClassAdded
                              ,'}'
                              , doubleCaption
    )
    cat(chunkRmdContent, file = chunkRmdFileName)
    
    log_debug("writing chunk {chunkId} to {chunkRmdFileName}" )
    if (is.null(names(chunkId))){
      chunkId <- setNames(chunkId, chunkId)
    }
    # str(chunkId)
    # log_debug("names of chunk {names(chunk)}" )
    
    # make slot for global myGlobalRmd R object
    chunkSection <- NULL
    tabbedPrefix <- ""
    if (doTabbed > 0){
      hashes <- paste0(rep("#", doTabbed), collapse = "")
      tabbedPrefix <- paste0("\n\n", hashes, " ", names(chunkId), "\n\n")
      # <- tabbedPrefix
      if (nchar(chunkPrefix)){
        chunkSection <- paste0("\n\n", hashes, " ", chunkPrefix, "\n\n")
      } else {
        chunkSection <- paste0(tabbedPrefix)#, '\n\n',chunkPrefix,' ', chunkId, chunkSectionModifier, '\n\n')
      }
    }
    
    child <- paste0(#"\n\n"
      chunkSection,
      "\n```{r child = "
      , '"', basename(chunkRmdFileName),'"'
      ,', out.width = "', childWidth2,'"'
      ,'}\n```\n\n'
    )
    # message(483)
    # print(child)
    myGlobalRmd[[repId]][chunkId] <- child
    myGlobalRmd <<- myGlobalRmd
    
    # if (writeImmediately) {
    #   writeRmd(myGlobalRmd[[repId]], myGlobalRmd[[repId]]$ffrmd)
    # # writeRmd(myGlobalRmd[[repId]])
    # }
  }
  
  
  if (!is.null(rmdText)){
    rmdText <- as.list(rmdText)
    # stopifnot(is.list(rmdText))
    # chunkId <- names(rmdText)
    myGlobalRmd[[repId]][chunkId] <- paste0(' ',unname(unlist(rmdText)),'\n')
    myGlobalRmd <<- myGlobalRmd
  }
  
  
  
  
  if (grepl("render", do)){
    log_info("vrmd| wd: {getwd()}")
    log_info("repId: {repId}")
    require(kableExtra)
    if ("openingChunk" == rev(names(myGlobalRmd[[repId]]))[1]){
      print("report not yet filled with elements beyond the header info")
    }
    if (writeImmediately) {
      headerData <- myGlobalRmd[[repId]]$headerData
      ddi <- dirname(myGlobalRmd[[repId]]$ffrmd)
      if (!dir.exists(ddi)){
        log_warn("dir created: {ddi}")
        dir.create(ddi, recursive = TRUE)
      }
      if (overwrite) {
        writeRmd(myGlobalRmd[[repId]], myGlobalRmd[[repId]]$ffrmd)
      }
    }
    # headerData <- myGlobalRmd[[repId]]$headerData
    
    # str(myGlobalRmd[[repId]]$ffrmd)
    # write Rmd file to disk
    
    # render Rmd
    log_info("rendering ------------ {myGlobalRmd[[repId]]$ffrmd}")
    log_info("rendering {myGlobalRmd[[repId]]$output_file} ....")
    # myGlobalRmd[[repId]]$ffrmd <- sub("~", Sys.getenv("R_USER", "~"), myGlobalRmd[[repId]]$ffrmd)
    # str(myGlobalRmd[[repId]])
    
    # newffrmd <- file.path(getCacheDir(), userName, "vrmdCache", basename(myGlobalRmd[[repId]]$ffrmd))
    # file.exists(ffrmd)
    # file.copy(myGlobalRmd[[repId]]$ffrmd, newffrmd, overwrite = TRUE)
    file.exists(ffrmd)
    myGlobalRmd[[repId]]$renderResult <- rmarkdown::render(
      # input = newffrmd
      input = ffrmd
      # , output_format = myGlobalRmd[[repId]]$output_format
      , output_dir = dirname(ffrmd)
      # , output_dir = dirname(newffrmd)
      , output_file = basename(myGlobalRmd[[repId]]$output_file)
      # , params = "ask"
      , quiet = quiet
    )
  }
  myGlobalRmd <<- myGlobalRmd
  
  
  if (grepl("view", do)) {
    if ("openingChunk" == rev(names(myGlobalRmd[[repId]]))[1]){
      print(paste("file name will be: ", myGlobalRmd[[repId]]$output_file))
      print("report not yet filled with elements beyond the header info, not viewing..")
      # return("warn")
    }
    # getOption("browser")
    browseURL(myGlobalRmd[[repId]]$renderResult)
  }
  
  
  if (grepl("reportpath", do)) {
    return(myGlobalRmd[[repId]]$output_file)
  }
  
  
  if (grepl("(push)|(copys3)", do)) { # |(render)
    log_info("vrmd line 874")
    if (!dir.exists(pushDir)){
      log_warn("dir created: {pushDir}")
      dir.create(pushDir, recursive = TRUE)
    }
    
    reportPath <- myGlobalRmd[[repId]]$output_file
    if (!length(pushReportFileName)){
      pushReportFileName <- basename(reportPath)
    }
    reportPathTo <- file.path(pushDir, pushReportFileName)
    log_info("vrmd line 885, reportPathTo =  {reportPathTo}")
    
    message("file to copy: ", reportPathTo )
    file.copy(reportPath, reportPathTo, overwrite = TRUE)
    res <- reportPathTo
  }
  
  
  if (grepl("copys3", do)) {
    log_warn("copyS3 disabled")
    # if (is.null(folderS3)){ return("no folder, not copied to S3")}
    # # if (!(toupper(Sys.getenv("USERNAME")) == "HHSCHE2") & .Platform$OS.type == "windows") {
    # #   log_warn("only for user HHSCHE2 or in cloud")
    # #   return(res)
    # # }
    # if (!length(S3reportFileName)){
    #   S3reportFileName <- basename(myGlobalRmd[[repId]]$output_file)
    # }
    # 
    # if (require(aphTsStore)){
    #   if (!length(storeReport)) {
    #     storeReport <- TSS3Store()
    #   }
    # } else {
    #   return("no package aphTsStore available")
    # }
    # 
    # if (is.null(storeReport$prefix)){
    #   log_warn("not copied, no prefix found in storeReport")
    # } else {
    #   dest <- file.path(storeReport$prefix
    #                     , reportBasePathS3
    #                     , folderS3
    #                     , S3reportFileName)
    #   log_info("file {myGlobalRmd[[repId]]$output_file} written to {dest}")
    #   res <- aws.s3::put_object(file = myGlobalRmd[[repId]]$output_file
    #                             , object = dest
    #                             , bucket = storeReport$bucket
    #   )
    #   myGlobalRmd[[repId]]$urlLink <- paste0(
    #     "https://aph.advancedgrowers.info/"
    #     , "app_direct/aph-cooking"
    #     , "/?_inputs_&sidebarCollapsed=false"
    #     , "&browseReportsModule-userFolder=%22", folderS3, "%22"
    #     , "&sidebarItemExpanded=null&V_close=0&tabs=%22browseReportsModule%22&V_save=0"
    #     , "&browseReportsModule-fileOi=%22", S3reportFileName, "%22")
    #   
    #   
    #   log_info("created url: {myGlobalRmd[[repId]]$urlLink}")
    # }
    # 
    # myGlobalRmd <<- myGlobalRmd
    # res <- myGlobalRmd[[repId]]$urlLink
  }
  
  if (grepl("dirs3", do)) {
    log_warn("copyS3 disabled")
    # if (require(aphTsStore)){
    #   storeReport <- TSS3Store()
    # } else {
    #   return("no package aphTsStore available")
    # }
    # dt <- as.data.table(
    #   getFolderIndex(storeReport, file.path(reportBasePathS3, folderS3))
    # )
    # keep <- c("Key", "LastModified", "Size")
    # dt <- dt[, ..keep]
    # return(dt)
  }
  
  if (grepl("www", do)) {
    # browseURL(myGlobalRmd[[repId]]$urlLink)
    res <- myGlobalRmd[[repId]]$urlLink
  }
  
  
  if (isTRUE(insideUI)) return(NULL)  
  return(res)
}


#' vrmdApp
#' @export
vrmdApp <- function(...){
  vrmd(cacheDir = "ReportsVRMD"
       , tmpdir = "ReportsVRMD"
       , pushDir = "ReportsVRMD"
       , project = "."
       , quiet = FALSE
       , ...)
}


ftlPalette <- function(name = c("primary", "secondary", "crop", "ftl")) {
  
  name <- match.arg(name, c("primary", "secondary", "crop", "ftl"))
  
  rgb255 <- function(...) grDevices::rgb(..., maxColorValue = 255)
  
  pal <- switch(name,
                "crop" = c(
                  "Cucumber" = cmyk(30, 0, 90, 0),
                  "Tomato" = cmyk(0, 100, 80, 0),
                  "Pepper" = cmyk(0, 55, 100, 0),
                  "Eggplant" = cmyk(56, 66, 25, 5),
                  "Rootstock" = cmyk(65, 0, 100, 7)),
                "primary" = c(
                  "PMS383" = rgb255(178, 187, 30),
                  "PMS5493" = rgb255(137, 187, 187),
                  "PMS377" = rgb255(120, 162, 47),
                  "PMS5767" = rgb255(106, 127, 65),
                  "PMS5757" = rgb255(130, 149, 98),
                  "PMS405" = rgb255(105, 94, 74)),
                "secondary" = c(
                  "PMS382" = rgb255(192, 215, 47),
                  "PMSCoolGray2" = rgb255(230, 231, 232),
                  "PMS649" = rgb255(222, 230, 243),
                  "PMS650" = rgb255(183, 206, 232),
                  "PMS159" = rgb255(227, 111, 30)),
                "ftl" = c(
                  "PMS3435" = rgb255(0, 81, 47),
                  "PMS471" = rgb255(205, 111, 25))
                
  )
  
  pal
  
}



#' vrmdQuick
#' 
#' @export
vrmdQuick <- function(repId
                      , reportTitle = repId
                      , outputFilename = paste0(repId, ".rmd")
                      , outputStyle = c("blank", "html", "word")[2]
                      , headerData = list(reportTitle = reportTitle
                                          , reportSubtitle = ""
                                          , reportAuthor = "Hans Schepers" #tolower(Sys.getenv("USERNAME"))
                                          )
                      , ...){
  g.addRmd <<- TRUE
  if (exists("g.repId", envir = .GlobalEnv)){
    rm(list = c("g.repId"), envir = .GlobalEnv)
  }
  #TODO clean?
  vrmdApp("init"
          , repId = repId
          , outputFilename = outputFilename
          , outputStyle = outputStyle
          , headerData = headerData
          , ...)
  .headerData <<- headerData
  g.doTabbed <<- 3
  g.repId <<- repId
}


cleanVRMD <- function(cachedir = getCacheDir() # "ReportsVRMD"
                      , full.names = TRUE
                      , pattern = "(.*\\.png$)|(.*[\\._=].*\\.Rmd$)", ...){
  ff <- list.files(cachedir
                   , full.names = full.names
                   , pattern = pattern
                   , ...)
  ff <- ff[!ff %in% c(".gitgnore")]
  for (fil in ff){
    file.remove(fil)
  }
  list.files("ReportsVRMD", full.names = TRUE)
}

